### ISSUE TITLE
Java 11 Support

### ISSUE THREAD

**Issue by onema** [JetBrains/kotless#40]
Hello, I tried to deploy a simple function and I initialized my Gradle project using Java 11, which is the latest supported runtime for Java in AWS Lambda. 

Everything got deployed correctly, except the AWS lambda runtime was set to `java8` and I got this error at runtime:

```
/HelloserverlessApplication has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

I'm using kotless `0.1.5` and the `spring-boot-lang` dsl.

**Comment by TanVD** [comment]
Fixed in dev. Runtime will be autodetected from Kotlin compiler target. It also can be specified directly in Gradle project.
Will be released in 0.1.6

**Comment by onema** [comment]
@TanVD do you know when `v0.1.6` will be released?

**Comment by TanVD** [comment]
I believe in a few days :) It is going to be "stabilizing" release :)

**Comment by matthewbartos** [comment]
I'm still getting this error @TanVD 😞 
Switching from version `11` to `1.6` fixes the issue
